CREATE TABLE `artale_equipment` (
  `equipment_id` int NOT NULL AUTO_INCREMENT,
  `equipment_type` varchar(255) NOT NULL,
  `weapon_type` varchar(255) NOT NULL,
  `armor_type` varchar(255) NOT NULL,
  `accessory_type` varchar(255) NOT NULL,
  `minimum_level` int NOT NULL,
  `weapon_att` int NOT NULL,
  `magic_att` int NOT NULL,
  `att_speed` int NOT NULL,
  `weapon_def` int NOT NULL,
  `magic_def` int NOT NULL,
  `warrior` tinyint NOT NULL,
  `magician` tinyint NOT NULL,
  `thief` tinyint NOT NULL,
  `pirate` tinyint NOT NULL,
  `archer` tinyint NOT NULL,
  `common` tinyint NOT NULL,
  `required_str` int NOT NULL,
  `required_dex` int NOT NULL,
  `required_int` int NOT NULL,
  `required_luk` int NOT NULL,
  `effects` varchar(255) NOT NULL,
  `upgrades` int NOT NULL,
  `npc_vendor_price` int NOT NULL,
  PRIMARY KEY (`equipment_id`)
)